const Glossary = {
  General: {
    Mana:
      "A Mana é um recurso natural, infinito, invisível como o ar e intocável como a luz, que pode ser sentido, absorvido e até manipulado internamente por alguns seres vivos aleatórios que já nascem com esta habilidade, mas muitos nunca descobrem em vida que eram capazes de tal. A absorção é lenta (3 de mana por rodada para seres vivos comuns) e cada indivíduo tem sua capacidade máxima de armazenamento no corpo (10 de mana para seres vivos comuns). Feitiços arcanos, que são mana concentrada e controlada, têm uma coloração Azul aos olhos humanos.",
    MageSorcerer:
      "É considerado um “Feiticeiro” aquele que nasceu com o dom de utilizar feitiços arcanos, independente de possuir alguma habilidade com o domínio das gemas. “Mago”, entretanto é aquele que consegue lançar magias através de seu controle das gemas elementares, e pode ou não ser um feiticeiro ao mesmo tempo.",
    Gemas:
      "Os corações de seres elementares, também chamados de gemas mágicas, são objetos finitos e indestrutíveis na natureza que contêm em si a consciência e o poder destes seres. As gemas só podem ser encontradas no interior de um ser elementar correspondente ao seu tipo, dentre os 7 possíveis. Depois que o corpo for suficientemente destruído ou o coração danificado, o elementar perde a capacidade de usar seu corpo, mas continua existindo dentro da gema. Quando um coração de elementar entra em contato com um ser vivo, eles são capazes de se comunicar telepaticamente, embora com muita dificuldade dependendo do quão forte é o elementar e o quão aberto à comunicação o ser vivo está. Os seres elementares só existem com o objetivo de propagar no mundo seus ideais, comportamentos e emoções, e também para ampliar o domínio de seu elemento em comparação aos outros. São seres muito inteligentes e, quando destruídos, observam e procuram por seres vivos com potencial de serem receptáculos compatíveis para utilizar seu poder e continuar a espalhar seu domínio pelo mundo de maneira indireta."
  },
  Attributes: {
    Constituicao:
      " Capacidade de suportar o cansaço até a exaustão. Resistência biológica a doenças, venenos e intoxicações. Pessoas de grande porte costumam ter uma constituição maior, e vice versa.",
    Forca: "Massa muscular é considerada como um todo, se alguém tem força alta, então isso se aplica a todos os músculos do corpo.",
    Destreza: " Ter músculos é uma coisa, saber usá-los é outra. Afeta coordenação motora, agilidade e perícia, especialmente com aquilo que envolve as mãos.",
    Esquiva:
      "Enquanto a destreza envolve mais agilidade com as mãos, pode-se dizer que esquiva envolve mais a agilidade com o corpo inteiro. Reflexo é sempre dependente da esquiva.",
    PoderMagico:
      " É como a “força” no uso da magia, o “músculo mágico”. Poder mágico envolve a intensidade/quantidade de magia que uma pessoa consegue exercer em uma conjuração",
    ManipulacaoMagica:
      "É como a “destreza” no uso da magia. O quão bem e com quanta precisão uma magia é conjurada depende deste atributo. Quando uma magia é realizada com uma intensidade trivial para aquele indivíduo, a manipulação mágica é o principal fator para definir o quão bem ela é feita.",
    Cautela: "Quando há algum sinal de perigo/emergência e a pessoa precisa prestar muita atenção nos seus arredores para não ser surpreendida.",
    Perspicacia:
      "Capacidade da pessoa de analisar as minúcias do ambiente, dos objetos e das pessoas em sua presença, tentando notar detalhes que não são óbvios a primeira vista.",
    Discricao: " O quão discreta uma pessoa consegue ser quando ela está intencionalmente tentando ser discreta.",
    Extravagancia: "O quanto uma pessoa consegue ser chamativa, atraindo todos os olhares para si, quando ela está intencionalmente tentando ser chamativa.",
    Resiliencia:
      "A resistência mental de uma pessoa. O quanto uma pessoa é afetada por dores emocionais e eventos trágicos. Em momentos de tensão, terror e desespero, como o psicológico da pessoa é afetado depende de sua resiliência."
  },
  Races: {
    Humano:
      "Iguais aos Humanos da vida real. Em aparência, há uma grande diversidade entre os humanos: nas ilhas de Sanichini eles são como asiáticos, cada ilha tendo suas peculiaridades, em San eles são 'japoneses', em Ichi são 'Filipinos' e em Ni são 'chineses'. No reino de Zardien os humanos são em sua maioria negros, com variadas tonalidades de cor de pele ao longo de todo reino. Em Northlön são quase todos de aparência mais 'europeia', embora haja também muitas pessoas de pele escura especialmente em alguns reinos ao sul do continente. Os Humanos se originaram tanto a partir do continente de Northlön quanto das ilhas de San-it-ni, eventualmente colonizando o continente de Gamênia e lutando por território e recursos contra os Lizardios e os Orcs. Estruturalmente, são todos Reinados pequenos com monarquias bem tradicionais, com casamentos entre famílias reais para formar alianças entre reinos e discussões sobre as legitimidades hereditárias que podem suceder em guerras. Para mais informações, acesse https://www.notion.so/regardsage/Civiliza-es-4f4ac4633f0d485fb07050f9e2d827ef#afe07af9f8aa4ef5acc1993b7769c74c ",
    Orc:
      "A maioria dos orcs possuem pele branca, um pouco acinzentada, e em alguns locais há variações de pele mais esverdeada, estes costumam ser ditos por 'abençoados pela natureza' e há diferentes interpretações culturais no significado de um orc com essa cor. 'Abençoados pela natureza' pode ser considerado tanto como uma maldição quanto um presságio de uma pessoa com um futuro importante ou um futuro trágico. Orcs mestiços com humanos podem ter pele marrom ou cinza escuro, e estes são vistos com muito preconceito por outros orcs. A massa muscular de um orc tende a ser muito maior do que a de um humano mediano, mas nem todos são tão fortes, apenas sua média é bem maior. Embora alguns fofoquem a respeito da falta de inteligência de um orc, em geral isso não é verdade e eles são tão capazes quanto humanos em assuntos intelectuais, porem sua produção tecnológica não é tão avançada e geralmente mais voltada para a guerra. Além disso, orcs são uma das raças com a menor qualidade de educação sobre magia, tendo somente uma universidade entre todos seus clãs, então é mais incomum encontrar algum com muita proficiência no assunto. Para mais informações, acesse: https://www.notion.so/regardsage/Civiliza-es-4f4ac4633f0d485fb07050f9e2d827ef#0ad05087eb5a4d9186a1070293831050",
    Lizardio:
      "Sua aparência lembra muito lagartos, olhos reptilianos, língua comprida e bifurcada, adoram se banhar no sol, são esguios e possuem uma longa e hábil cauda. Porém lizardios são também muito conhecidos por sua pele escamada, que confere a eles uma resistência física natural maior do que todas as outras raças civilizadas. Dito isto, por baixo de suas escamas Lizardios tem uma carne mole e mais frágil do que os humanos, tornando escamas quebradas um ponto fraco letal. Lizardios podem ter chifres de muitos formatos diferentes, e muitos nem tem, mas em geral seus chifres são curtos. As escamas dos lizardios os conferem uma grande resistência aos raios do sol, mas depois de dias de insolação eles adoram ficar de molho em água morna por horas para se hidratar. Para mais informações, acesse: https://www.notion.so/regardsage/Civiliza-es-4f4ac4633f0d485fb07050f9e2d827ef#292887bc71c44711b3eb7e9e96a69898",
    Underall:
      "São pequenos, em torno de 1,20m, e possuem uma clara e frágil pele que se queima fácil contra o sol, criando bolhas e inflamando. Ao longo de suas costas corcundas, nuca, antebraço e no topo da cabeça possuem uma camada de exoesqueleto que é um couro muito resistente, fruto de má formação em seus corpos artificiais que foram criados em laboratório. Possuem pelo corpo alguns poucos pelos espalhados, especialmente no rosto e seus braços e pernas são magros e ágeis, além de seu corpo ser bem leve. Underall não gostam de sol e por isso vivem majoritariamente embaixo da terra, saindo para a rua somente cobertos com longos mantos e capuzes, a não ser em algumas partes de maior latitude do mundo onde o sol é mais tolerável. Sua alimentação é baseada em cogumelos, insetos, minhocas e alguns outros tipos de plantas, mas são onívoros e podem comer quase qualquer comida estrangeira, com exceção de carnes gordurosas que são muito difíceis de digerir. Sua destreza manual e conhecimento técnico é muito maior do que a maioria. Algumas pessoas dizem que underall se parecem com ratos bípedes... mas eles não gostam nada desta comparação. Para mais informações, acesse: https://www.notion.so/regardsage/Civiliza-es-4f4ac4633f0d485fb07050f9e2d827ef#539ad4df65284af3b8395df459ac4ed7",
    Griffin: "Descrição física- Cabeça e asas de águia/ falcão, quadrupede com pernas, tronco e calda de leão, mas revestido de penas",
    Songster:
      "descrição física- semelhantes a humanos, com três diferenças: todos são mudos(?), têm cabelos coloridos e suas mãos são constituídas de dois polegares, dois indicadores e dois dedos médios, como se fosse espelhada no meio de sua palma, tendo um polegar de cada lado.",
    Halfling: "",
    Telno:
      "Criaturas consideradas muito diferentes e esquisitas pela maioria das raças civilizadas, pois são polvos muito inteligentes que vestem roupas e caminham como humanoides. seus 10 tentáculos são frágeis e se dividem em 4 membros para melhorar sua destreza manipulando objetos e caminhando para se parecerem mais 'bípedes'. O verdadeiro habitat de um telno é no fundo do mar, onde sua agilidade é imensa e podem nadar em alta velocidade, mas os telnos 'caminhantes' que nasceram e viveram toda suas vidas na terra firme estão acostumados a caminhar como outras raças. Sua habilidade manuseando objetos é bem diferente, considerando que seus tentáculos podem grudar fortemente em objetos, mas sua força física não é muito grande. A sucção proveniente dos tentáculos também permite aos telnos escalarem paredes e até se pendurarem no teto, com mais facilidade quando não estão usando roupas, mas obviamente este tipo de comportamento não é comum. Embora consigam respirar fora da água, o corpo dos telnos é muito dependente de água para não ficarem ressecados e desidratados, necessitando longos banhos e muita ingestão de líquidos. A cor da pele dos telnos é azul escuro, mas todos possuem capacidade de se camuflarem, mudando suas cores, embora só consigam escolher uma única cor para o corpo inteiro, ou seja, não é possível se camuflar perfeitamente formando padrões diferentes de cores e texturas ao longo do corpo. Um telno macho e fêmea são extremamente difíceis de se diferenciar e normalmente só um telno consegue perceber a diferença, causando muita confusão nas outras raças por não saberem qual pronome usar, mas os telnos não se importam realmente com isso visto que sua cultura não diferencia homens e mulheres a não ser por motivos sexuais. Para mais informações, acesse: https://www.notion.so/regardsage/Civiliza-es-4f4ac4633f0d485fb07050f9e2d827ef#34cf3298f8f0480e887b60cc8ee4ea86",
    Raven: "",
    Dragao: ""
  },

  Civilizations: {
    Nordico:
      "Presentes no continente de Northlön, se dividem em dezenas de reinos que dominam diferentes províncias do continente. As disputas por território são sempre presentes, sem haver nenhum reino imensamente superior a todos os outros (atualmente), mas a maioria destes reinos se encontram em tempos de paz e prosperidade entre si, o que mais mantém guerras em ciclo são as históricas rivalidades entre algumas das nações e a ambição por poder e controle de alguns monarcas. A herança do trono se da pelo filho homem mais velho, priorizando o filho mais velho sobre o irmão mais velho. Os reinos humanos possuem diplomacias externas independentes uns dos outros, mas em geral todos são inimigos dos Orcs, pois esses são extremamente agressivos contra qualquer Humano. Além disso a maioria dos reinos possui amizades com as outras raças, porém relacionamentos mais ásperos com Sulistas e Lizardios.",
    Sulista:
      "Vivem nas ilhas de San, Ni e Ichi, com maior concentração de população na ilha San. As ilhas possuem um Reino cada, com culturas e costumes diferenças, fortes variações linguísticas e visíveis diferenças na aparência, embora outras raças digam que 'Sulistas são todos iguais', eles não são. Alguns escutam Kpop. Os reinos das ilhas de San, Ni e Ichi chamam-se, respectivamente, Nizon, Ka-wo e Ichao. Estes reinos também possuem colônias no continente de Gamênia, mas menores do que as dos nórdicos, e muito menos unidas. As cidades colônia daquele local são estritamente costeiras e servem o propósito de serem cidades portuárias e de abastecimento aos que por ali navegam. Os Sulistas possuem rixas políticas muito fortes entre si, muito raramente se aliando, o que os torna vulnerável ao poderoso império dos Lizardios, por isso não ousam adentrar muito o continente. Ao invés de resolver suas disputas em guerras entre si, os reinos Sulistas são extremamente competitivos e tentam demonstrar sua superioridade através de produção de conhecimentos, arte, tecnologia, vitórias em esportes e construção de palácios e templos exorbitantes. Diplomaticamente, os Sulistas tentam não conflitar muito com outras raças, pois já tem problemas o suficiente entre si, com exceção dos Lizardios. A busca por expansão dos Sulistas é limitada pelo poderio militar dos Lizardios e estes só não retaliam o Sulistas porque não possuem uma frota naval e consideram os Orcs uma ameaça muito maior. Os Sulistas não possuem muitas alianças, além dos [humanos do continente do meio] com quem tem um forte comércio. Também há teorias conspiratórias de que o reino de Ka-wo possui alianças secretas com os Dragões, o que os tornariam inimigos de todas as raças do mundo se fosse verdade. Em hereditariedade, é priorizado irmãos mais velhos acima de filhos mais velhos.",
    Zardienense:
      "Vivem nas ilhas de San, Ni e Ichi, com maior concentração de população na ilha San. As ilhas possuem um Reino cada, com culturas e costumes diferenças, fortes variações linguísticas e visíveis diferenças na aparência, embora outras raças digam que 'Sulistas são todos iguais', eles não são. Alguns escutam Kpop. Os reinos das ilhas de San, Ni e Ichi chamam-se, respectivamente, Nizon, Ka-wo e Ichao. Estes reinos também possuem colônias no continente de Gamênia, mas menores do que as dos nórdicos, e muito menos unidas. As cidades colônia daquele local são estritamente costeiras e servem o propósito de serem cidades portuárias e de abastecimento aos que por ali navegam. Os Sulistas possuem rixas políticas muito fortes entre si, muito raramente se aliando, o que os torna vulnerável ao poderoso império dos Lizardios, por isso não ousam adentrar muito o continente. Ao invés de resolver suas disputas em guerras entre si, os reinos Sulistas são extremamente competitivos e tentam demonstrar sua superioridade através de produção de conhecimentos, arte, tecnologia, vitórias em esportes e construção de palácios e templos exorbitantes. Diplomaticamente, os Sulistas tentam não conflitar muito com outras raças, pois já tem problemas o suficiente entre si, com exceção dos Lizardios. A busca por expansão dos Sulistas é limitada pelo poderio militar dos Lizardios e estes só não retaliam o Sulistas porque não possuem uma frota naval e consideram os Orcs uma ameaça muito maior. Os Sulistas não possuem muitas alianças, além dos [humanos do continente do meio] com quem tem um forte comércio. Também há teorias conspiratórias de que o reino de Ka-wo possui alianças secretas com os Dragões, o que os tornariam inimigos de todas as raças do mundo se fosse verdade. Em hereditariedade, é priorizado irmãos mais velhos acima de filhos mais velhos.",
    Garnak:
      "Este clã foi o mais afetado pelas invasões de território dos Humanos e por isso são os mais raivosos e agressivos sobre tudo que diz respeito a Humanos e mestiços. Um clã despedaçado pelas constantes guerras, valoriza muito a força de um Orc e estimula todos a procriarem o maximo possivel. Sua economia é quase toda voltada a guerra. Um dia este já foi um grande clã, com frotas navais e uma cultura voltada a pesca, hoje mais da metade de sua comida tem que ser comprada de outros clãs e sua economia é fortemente dependente da guerra, vendendo espólios conquistados depois de batalhas e assaltando plantações dos humanos, além da forte cultura de caça a animais. Em ambição por poder, é muito comum Orcs Garnak estudarem as artes mágicas para usá-las contra humanos e lizardios.",
    Bothra:
      "O único clã que não está em guerra com o reino de Zardien, seguem os ensinamentos de um sábio Orc sacerdote que possui um século de idade, lutam apenas para defender seu território e conseguiram criar uma perigosa e complicada relação com os Humanos para que possa existir comércio entre os dois. O trato que existe é que apenas mestiços de Orcs e Humanos podem adentrar o território do clã, trazendo e levando produtos. Os outros clãs não gostam muito deles por isso, chamam-os de traidores. O clã Bothra é o segundo maior e possui uma grande variedade de pecuária, uma culinária famosa e castelos grandes e bem fortificados.",
    VulNesMai:
      "Ao longo dos últimos séculos, este clã tem conseguido a amizade dos Griffin e desenvolvido uma relação que resultou no maior acúmulo intelectual sobre magia entre todos os Orcs. A capital dos Vul Nes Mai, Vul Tiran, é de longe a maior universidade de magia entre os Orcs. Orcs de todos os clãs desejam estudar as artes neste local, mas seu acesso é limitado a um contrato que obriga o Orc a nunca se levantar em guerra contra o clã Vul Nes Mai. Alguns respeitam muito clã por sua dedicação a tecnologia e a sabedoria, outros os veem como Orcs esquisitos e motivo de piada. Os Vul Nes Mai tentam implementar o uso de magia arcana e elemental em sua sociedade para criar o melhor ambiente possivel para seus cidadãos. Seu poder militar é quase todo focado no uso de magia mas também são conhecidos pela grande produção de artesanatos de qualidade, especialmente os de madeira. As únicas coisas que impedem este clã de ser o mais poderoso é sua pequena população e sua impopularidade entre muitos Orcs.",
    Drukan:
      "O maior de todos os clãs, tanto em território quanto em exército. Este clã é há muito tempo o mais forte de todos, mas mesmo nas guerras internas dos Orcs eles não são capazes de vencer com muita frequência. Um dos motivos é seu ambicioso e ingênuo líder, o outro é que os Orcs tem conhecimento sobre a ameaça que os Drukam são e quando é necessário se unem para lutar contra eles para impedir uma dominação total. Além de sua força militar, o que mantém o clã acima dos outros é sua potente economia, fortecida pelo comércio com os Underall, que compram dos Durkam metais preciosos que são encontrados em seu território. A aliança entre os dois é tão forte que os Durkam permitem que os Underall construam pequenas vilas ou locais comerciais fora e até dentro de suas cidades. O comércio é mutuamente beneficente, mas como os Underall também possuem relação com os Lizardios, existem influencias políticas que fazem os Lizardios pensarem duas vezes antes de atacar uma cidade com uma considerável população de Underall. Os Durkam são os que possuem a civização mais organizada, incluindo grandes assembleias para decidir as próximas ações do clã e quando o lider da família principal morre, são feitas eleições para decidir quem o sucederá, mas penas é legítimo outros parentes da família principal.",
    WortHem:
      "Este clã domina completamente a costa oeste de Kréc'tan, se auto denominam os 'donos dos mares do oeste', e são o principal motivo do por que nenhuma outra raça se atreve a navegar por aqueles mares. Muitos fora da lei deste clã se tornam piratas que saqueiam embarcações por todo o continente ou das ilhas dos Songsters e dos Halflings, mas oficialmente o clã utiliza seu poder para atacar os territórios Lizardios que são na costa ou acessíveis por rio. Este clã possui muitos problemas internos de disputa por poder pelos vários membros da família chefe que desejam liderar o clã um dia. É um clã com muito potencial mas o futuro dele depende de quem será o próximo lider e que objetivo dará ao clã."
  },

  GeneralSpells: {
    Starter: {
      Telecinese:
        "Faz um objeto dentro de 4 metros levitar e move-o ou dispara-o em alguma direção. Peso máximo: +-30 quilos. Custa mana para apenas mover o objeto e mais ainda para dispará-lo. Pode mover/disparar 2 objetos ao mesmo tempo, pelo dobro de mana.",
      Repulsao:
        "Concentra todo seu mana e o dissipa instantaneamente, em uma explosão de energia partindo de uma das mãos afasta para longe com força tudo que estava próximo. Exauri toda a mana do usuário de uma vez só, quanto menos mana ele tiver gasto antes de usar o feitiço mais forte vai ser a explosão. ",
      CaminharNaAgua:
        "Aumenta a suavidade de suas caminhadas para que elas não consigam quebrar a tensão superficial de líquidos e você possa caminhar livremente sobre eles. Correr torna o feitiço mais difícil de ser realizado, assim como carregar muito peso. O feitiço precisa ser canalizado.",
      Telepatia:
        "Permite que você entre na cabeça de uma pessoa para conversar com ela usando apenas os pensamentos. Em geral só funciona em pessoas que permitam que você entre em suas mentes, mas com muita dificuldade você pode tentar invadir a mente de alguém, mas a pessoa saberá quem está fazendo isso. Uma técnica muito mais avançada deste feitiço envolve usá-lo para tentar ler os pensamentos de alguém, mas isso é extramente difícil, é necessário muitos anos de prática e mesmo assim é muito confuso de tentar entender o pensamento ou memória de outra pessoa. O alcance do feitiço varia muito. O mais seguro é usá-lo enquanto toca na pessoa, quanto maior a distância mais difícil, mas se a pessoa estiver permitindo que você entre em sua mente e vocês dois já se conhecem muito bem, possuem muita intimidade ou uma conexão pessoal muito forte, o alcance do feitiço pode aumentar a até centenas de metros.",
      Clarividencia:
        " A partir de alguns momentos de leve meditação consegue se concentrar em algum lugar que já esteve antes para enxergar o que está acontecendo lá, até mesmo ouvir e sentir cheiros. Quanto mais longe o local de onde você está, mas difícil é realizar o feitiço e compreender a situação, mas quanto mais o local for familiar ao feiticeiro, mais fácil é de realizar o feitiço. Outros feiticeiros que estejam no local conseguem sentir que estão sendo observados.",
      Cleptomania:
        "Ao toque, permite o feiticeiro teleportar um objeto pequeno para um espaço interdimensional que apenas você tem acesso. Enquanto esconde o objeto neste espaço, você consome mana lentamente, e consome mais mana para cada objeto ou tamanho de objeto que teleportar. Não é possível teleportar objetos grandes ou seres vivos.",
      ExplorarPensamentos:
        "Permite o feiticeiro adormecer de maneira semi consciente para revisitar uma de suas memórias, mesmo que antigas, e explorar tudo aquilo que viu ou ouviu e pode talvez não ter prestado muita atenção no momento. Existe a possibilidade para um feiticeiro muito experiente, provavelmente arquimago, de combinar este feitiço com o de telepatia para invadir a mente de uma pessoa e reviver as memórias dela."
    },
    Advanced: {
      ImplosaoEspacial:
        " O usuário teleporta-se até um local dentro de 4 metros e no lugar onde estava antes é criado uma explosão de energia que causa dano a todos em 1 metro em volta, empurrando-os para longe. Não é possível desviar.",
      AuraDeEnergia:
        "Uma energia arcana que parece com fogo envolve todo o corpo do lançador durante 4 rodadas. Se durante esse tempo ele for atingido por um ataque físico, a energia arcana se jogará contra o atacante para empurrá-lo para longe e desequilibrá-lo.",
      ChuvaDeDestruicao:
        "Dispara, a partir de suas mãos, 5 lasers de energia arcana que causam cortes profundos e penetrantes. Pode mirar em vários alvos ao mesmo tempo, dentro de 5 metros, em qualquer direção. Aumenta/diminui em 1 o número de disparos para cada ponto de Poder Mágico. O dano de cada corte é consideravelmente grande, mas são difíceis de acertar."
    }
  },

  Plants: {
    Flouren:
      " Cogumelo verde fluorescente que cresce em locais escuros e profundos, não é comestível e costuma atrair insetos para sua luz. Originalmente Flourens eram raros e desconhecidos por todo o mundo, até que os underall o encontraram em uma caverna subterrânea muito profunda junto de formigas de lava. Após replantarem muitas vezes estes cogumelos, depois de séculos ele se tornou conhecido no mundo todo e uma ferramenta de iluminação padrão nas cidades subterrâneas do território underall. ",
    Perilacea:
      "Uma erva parecida com capim, muito comprida, se divide em 3 na ponta e  cresce em matagais, fácil de encontrar em maior parte do mundo. Chá de Perilácea é popularmente usado na medicina para ajudar a digerir e limpar o estômago, mas se a dosagem for muito grande causa fortes diarreias. Pode ser misturada com pó de osso e qualquer tipo de liquido ácido para criar um veneno que destrói o estômago de uma pessoa, causando hemorragia interna e matando em até uma hora.",
    Herim:
      "Grande flor branca abençoada pela luz, usada popularmente como decoração de templos da luz e como um pequeno amuleto para afastar demônios (só funciona realmente contra demônios pequenos). Celestiais da raça Sprite vivem dentro dessas flores em locais afastados da civilização.",
    Corus:
      "Uma família especial de cogumelos que crescem em regiões frias, sua estipe é feita de alguma planta leguminosa como cenoura ou batata (Córus-cenoura, Córus-batata), tendo apenas um pequeno pedaço do legume visível fora da terra. Além de se alimentar de nutrientes da terra, os Córus absorvem restos de animais como pele, carne e sangue, sendo este o principal adubo para fazê-los crescer. É um fungo popular entre os raven, sendo considerado benção sagrada e é parte de rituais religiosos, onde no fim de cada dia os raven jogam restos de animais em suas plantações de Córus para abençoa-los com muitos legumes. Córus é um dos principais alimentos entre os raven.",
    Surinan:
      "Uma árvore considerada como praga em todo o mundo, mesmo entre druidas quando esta árvore é avistada é recomendável que seja cortada imediatamente. Suas raízes são finas compridas e se alargam muito, roubando nutrientes de outras plantas por perto. Seu tronco é fino e cresce muito rápido, se apoiando em outras árvores próximas, quase como uma trepadeira que não se enrola, e a altura máxima da Surinan pode ser tão grande quando um eucalipto e suas folhas são largas como uma palmeira, criando áreas com muita sombra, impedindo que outras plantas mais baixas recebam luz. Sua proliferação se da por Anemocoria. É encontrada principalmente em Northlon e Gamênia, mas não é comum pois são desvastadas assim que são encontradas, se não todas as plantas na região morrem.",
    Trigalia:
      "Árvore de tronco laranja, com madeira muito mais maleável que o comum. Seus vários galhos são finos e compridos, assim como o tronco, e quando venta a Trigália chacoalha por muito tempo. É repleta de acúleos tanto no tronco quanto nos galhos. Popularmente é dito que as Trigálias são arvores dançantes que não gostam de ser interrompidas, chegar perto delas enquanto dançam causa muitos cortes superficiais. A madeira delas é comumente usada para fazer navios, arcos e flechas, por conta de sua maleabilidade.",
    Oriçua:
      "Mais popularmente conhecida como 'Pitanga Mortífera', é uma frutinha rosa muito rara, só encontrada em ilhas a nordeste de Sanichini. Tanto animais burros quanto criaturas inteligentes rapidamente aprendem que esta planta é muito perigosa: se comer apenas algumas Oriçuas terá enjoos por algumas horas, sintoma inicial da fruta, e depois de muitas horas irá vomitar sangue rosado, que é o momento em que as dores começam e o destino da pessoa já está selado, e pouco depois morre. A semente de Oriçua na verdade é comestível sem problemas, o veneno está na pequena quantidade de líquido dentro da fruta.",
    Xascenne:
      "Uma alga marinha muito grossa e feita quase toda de água, encontrada nas profundezas do oceano, mercadoria que telnos costumam comercializar. Quando seca, a alga fica muito fina e tem a única propriedade de absorver líquidos a sua volta, muito mais rápido que uma esponja, e inclusive absorve a umidade no ar, deixando o ambiente seco depois de horas. A cor da Xascenne também pode ser usada para indicar se a água tem algum tipo de contaminação.",
    Flaminga:
      "Flor vermelha que diz-se ser abençoada pelo fogo, é encontrada apenas na terra de regiões vulcânicas e mesmo nelas é rara. A flor é completamente imune a chamas, quando alguém ateia fogo em uma Flaminga, em questão de segundos o fogo se apaga. É uma exótica planta de alto valor.",
    Mandes:
      "Família de flores que se parecem com repolhos, com um núcleo grande envolto por varias camadas de pétalas marrom. As pétalas de Mande são carregadas de gases que são liberados caso algo colida com elas, usado pela planta como autodefesa de predadores. O núcleo do Mande é comestível, e bem saboroso, mas é necessária uma técnica muito específica para conseguir cozinha-lo de maneira que não seja tóxico, o clã orc Bothra é conhecido por ter muitos cozinheiros que conhecem bem esta técnica. Há duas variações de Mande: o Mandalul, que possuí um gás alucinógeno mas que pode causar danos permanentes ao pulmões de quem o inspira, embora exista uma droga chamada 'Paraíso' que é feita a partir desta flor de maneira que fique ainda mais alucinógena e menos tóxica; e o Mandel, cujo gás tem uma toxina que inflama temporariamente a garganta da pessoa por algum tempo, causando dificuldades respiratórias e depois de algumas horas cria bolhas de pus dentro do estômago, matando a pessoa internamente com sua acidez. As bolhas de pus podem ser evitadas com muita ingestão de água.",
    Robara:
      "Com a casca mais dura e o interior mais mole do mundo, esta árvore é muito única pois serras e machados normais tem muita dificuldade de cortá-la, levando um dia inteiro ou até mais para cortar uma única delas. A unica coisa que consegue cortar com um pouco mais de eficiência sua casta são as serras automáticas dos underall, tornando esta madeira e casca um produto quase exclusivo deles. O interior da Robara branco e mole como um aipim, podendo ser comido depois de cozido, mas não é muito saboroso, os underall são os únicos que apreciam esta comida exótica. A casca da Robara pode ser usada como revestimento para tornar algo mais resistente, e é comum que algumas tribos druidas utilizem um feitiço secreto que enfraquece as plantas para conseguir extrair essa casca e revestir suas roupas de couro para fazer armaduras.",
    Lazir:
      "Flor azul que fica aberta para absorver sons altos ao seu redor e então guardando-os internamente. Quando alguém encosta na Lazir fechada ela se abre e solta o som guardado, geralmente espantando animais e até assustando pessoas. Diz-se que esta planta tem propriedades mágicas que a permite guardar os sons, possivelmente abençoada pelo deus dos ventos.",
    Talanua:
      "Planta trepadeira comum em Northlon que cria pequenos arbustos ao longo de suas raízes e neles crescem Talans, frutas azuis suculentas que podem ser comidas, mas não são gostosas nem nutritivas, porém podem também ser usadas para fazer tinta azul.",
    Karnes:
      "Um tipo de aguapé encontrado em lagos por toda gamênia, possuí um botão branco pequeno no seu topo. Karnés são atraídos por magia arcana e irão flutuar lentamente na direção de onde um feitiço foi lançado ou de uma fonte de magia. É usado em laboratórios experimentais usando sua velocidade de atração para quantificar a quantidade de energia arcana produzida por um feitiço ou objeto mágico.",
    Emilval:
      "Árvore negra tanto por fora quanto por dentro, com folhas sempre de cores outonais amarelas ou vermelhas. Sua seiva é branca e muito ácida, usada bastante como reagente químico. Beber sua seiva é extremamente danoso a qualquer criatura. Encontrada principalmente no território dos Raven ou no extremo norte de Northlon.",
    Malagua:
      "Mais conhecida como 'Pimenta de Dragão' tem o formato de uma pequena cenoura vermelha e pode ser encontrada em toda Gamênia, principalmente na região central. Sua pimenta é muito forte e a maioria das raças não conseguem tolerar comê-la, mas os lizadios tem resistência maior a este efeito e usam-na frequentemente como tempero. Ao morder Malaguá, uma pequena quantidade de gás inflamável e ardente é liberado, que quando expirado pode causar uma pequena e rápida baforada de fogo caso a pessoa assopre em frente a uma fonte de fogo. ",
    Zorlau:
      "Algas marinhas azuis com muitos pequenos cristais que armazenam uma pequenina quantidade de magia arcana, criando um brilho natural. Eram plantas somente encontradas nas grandes profundezas do alto mar, mas há muito tempo os telnos trouxeram esse espécime para Telnia e reproduziram-no em suas cidades, tornando-se uma 'praga' tão forte que se espalhou também para as redondezas de Telnia, e hoje é parte integral de sua civilização, sendo uma luz natural encontrada por toda parte. A quantidade de magia arcana armazenada por cada alga é muito ínfima para que seja relevante de alguma maneira. Durante alguns dias, uma vez por ano, acontece o evento chamado de 'O Encantar das Praias' pelos humanos ou 'O Renascer da Luz' pelos telnos, onde todas Zorlau desprendem seus cristais e começam a crescer novos, os cristais então flutuam até a superfície da água e são levados pela maré até as praias de Northlon onde os oceanos brilham em uma forte luz azul e quando chegam nas areias os cristais se quebram e liberam sua energia de volta para a natureza. Durante este evento anual, as praias ficam carregadas de uma poderosa aura de energia arcana, potencializando enormemente qualquer feitiço lançado no local.",
    Ophiocardo:
      "Um fungo que cresce a partir de cadáveres de pessoas infectadas e espalha seus esporos para qualquer um que chegue perto, infectando-os. A única maneira de tratar a infecção do parasita é aquecendo o corpo da pessoa a temperaturas perigosamente altas. Se não for tratada rápido, a pessoa pode sofrer danos permanente ao cérebro. Se nunca for tratada, o parasita ataca o cérebro com 'raízes', deixando-a zumbificada e sem autocontrole, eventualmente a pessoa morre e em seu cadáver cresce em 1 dia um novos talos com esporos para afetar novas pessoas. É encontrado somente nas ilhas e costa a noroeste de Gamênia, os orcs que vivem na região tem pleno conhecimento que o cadáver de alguém infectado deve ser queimado assim que a pessoa morrer.",
    Babuim:
      "Planta rasteira similar a uma Babosa que cresce em regiões montanhosas, especialmente ao norte de Gamênia, que possui folhas grossas parecidas com tentáculos verdes. Seu interior contém um líquido pastoso chamado de 'Cera de Babuim' que pode ser usado medicinalmente para tratar ferimentos e pode ser usado para fazer velas. Entretanto, a sua cera é levemente alucinógena, então uma vela funciona como incenso contagiante. É utilizada culturalmente entre os griffin para fazer rituais ou como simples iluminação.",
    Heraquita:
      "Conhecida por todas as raças como 'Dente de Songster' (exceto pelos songster, que não gostam desta apologia) é um dente-de-leão com plumas coloridas, como um arco-íris, mas que pode causar forte reação alérgica em algumas pessoas. Encontrado em ilhas e praias de regiões tropicais.",
    Calicgo:
      "Um trigo especial, da cor ciano, que fermenta muito mais que trigo comum, o que o torna um reagente químico interessante mas também um ingrediente diferente para se usar na produção de massas e pães, pois estes terão um teor alcoólico razoavelmente alto, podendo até embebedar uma pessoa que comer demais. Seu plantio é comum em largos campos de clima temperado."
  },
  Potions: {
    Trutum: "1 truta + sangue de coelho + medula de hiena. = transforma quem beber em uma truta por 12 horas.",
    FalantisBeings:
      "cabeça de papagaio + cogumelos alucinógenos colocados em água fervendo. Mecha bastante e coloque uma pitada de pelo de macaco. = Transforma permanentemente a traquéia de um animal, possibilitando que ele fale.",
    Revertek:
      "Coração esmagado de felino + raiz esmagada de uma arvore com mais de 5 metros de altura. Coloque a mistura em um frasco com sangue de um humano com 8 ou menos de inteligência. = Reverte o efeito de outras reações químicas. (felinos grandes rendem 3 frascos)",
    Radaris:
      "molhe a orelha de um morcego com sangue de aranha e coloque em um frasco com qualquer bebida corrompida por trevas. = Fica cego por 15 minutos, mas consegue sentir a presença de qualquer coisa que esteja a menos de 20 metros de distância. (aranhas e morcegos gigantes fazem 3 frascos )",
    Getriquis:
      "triture 1 dente grande de tigre ártico e coloque em uma mistura de saliva de formiga de formiga ártica gigante com seiva (de qualquer árvore) = A pasta cinza “crocante” resultante por ser derramada e grudada em um objeto para congelar uma pequena camada da superfície de água que entre em contato com o objeto.",
    Lytogrow:
      " coloque uma folha de árvore qualquer que tenha sido encantada pela luz/trevas dentro de caldeirão de sangue de dragão (cada dragão rende 1 caldeirão). A reação comprime e condensa o sangue em uma quantidade que cabe em um frasco, também tornando o líquido verde brilhante. = derramar o frasco em terra faz crescer instantaneamente uma árvore falante (do mesmo tipo da folha usada) que defende a luz/trevas com sua vida.",
    Transmog:
      "um pedaço de pele de doppleganger + um tufão de pelo de alguma criatura+ uma bebida alcoólica bem forte = Transforma-se na criatura que o pelo foi retirado durante 1 hora.",
    Burblam:
      "1 asa de serpente voadora picada em pedaçinhos + água de coco misturados em água do mar = quando fervido, o frasco libera bolhas gigantes (de 1-2 metros de diâmetro) que só estouram quando são golpeadas por algo pontiagudo.",
    Pyrotic:
      " 2 linguas de hellhound + 4 penas de fênix + 1 gema de fogo = transforma novamente a gema para ter outra aparência. O novo formato da gema torna o usuário e seus pertences imunes a fogo, além disso o objeto fica passivamente em chamas.",
    Sulfric:
      " ataduras de múmias + saliva de worm + limão/maracujá = um ácido que derrete completamente qualquer superfície. (causa 1D12*10 de dano)(1 frasco para cada worm)",
    Unmortalis:
      "1 cérebro de zumbi+ pó de fada + sangue de baratas = uma poção que faz o usuário ficar morto por X horas (1 hora para cada barata usada) e depois acorda como se nada tivesse acontecido.",
    Oilis:
      "banha de ogro + tinta de kraken + suco de qualquer fruta = um óleo super escorregadio que é basicamente impossível ficar em pé em cima. (1 ogro e 1 fruta rendem 1 frasco, enquanto tinta de um kraken rende para 10)(cada frasco cobre uma área do chão de 2m X 2m)",
    HealingPotion:
      "10 folhas de ervas medicinais esmagadas e misturadas em 250ml de sangue humano com um coração inteiro de javali. = Aumenta fortemente a capacidade regenerativa de uma pessoa por uma hora.",
    Humantri:
      "1 Osso triturado de esqueleto que tenha sido reanimado por necromancia + água salgada + 4 chifres de devilish colocados de molho por 2 horas. = Um líquido relaxante que quando derramado em cima de um objeto da a ele a habilidade de falar, pensar, e lembrar de tudo que aconteceu em sua “vida”. [dura infinitamente]"
  }
};

module.exports = Glossary;
